### ISSUE TITLE
dashboard broken

### ISSUE THREAD

**Issue by mrafieee** [finn-no/grafana-dashboards#5]
1. Netstat (Established)
2. UDP stats (InDatagrams, InErrors, OutDatagrams, NoPorts)

are not working should we enable specific flag for data gathering?

**Comment by knutemann** [comment]
Hi,

I am not aware of any issues regarding those metrics. Is the node exporter providing you the metrics? node_netstat_Udp_InDatagrams, node_netstat_Udp_InErrors, node_netstat_Udp_OutDatagrams, node_netstat_Udp_NoPorts and node_netstat_Tcp_CurrEstab ? Might it be that you are running node exporter as an user not being able to collect those metrics?


-- 
Knut
