### ISSUE TITLE
Network Traffic Interfaces

### ISSUE THREAD

**Issue by madmanidze** [finn-no/grafana-dashboards#6]
Hello

How add more interfaces like em2, not just eth0 ?

Thank you.

**Comment by knutemann** [comment]
Hi,
If the prometheus node exporter is serving the metrics in the same manner for those interfaces as for eth.* it should just work. Have you verified that you have node_network_receive_bytes and node_network_transmit_bytes metrics for your interfaces?


-- 
Knut
