### ISSUE TITLE
Many metric names have changed in latest node_exporter

### ISSUE THREAD

**Issue by mrobbert** [finn-no/grafana-dashboards#9]
The 0.16 release of node_exporter has changed many metric names to include base units. I was able to manually fix this on the dashboard within my installation, but exporting that doesn't give me a clean diff to submit as a patch. Let me know if you'd like me to try to put together a patch, but it may be just as easy for you to take a look at the node_exporter changes and fix it yourself.

**Comment by alantang888** [comment]
You may try my PR #8 .
Hope can help you.

**Comment by knutemann** [comment]
I've merged PR #8 .

**Comment by mrobbert** [comment]
Finally got a chance to test this and it worked, but I see that you already merged the change so this is kind of redundant, but I wanted to let you know that it did work for me.
